# fly.toml app configuration file generated for table-api on 2023-10-21T14:56:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "table-api"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  
